openapi: 3.0.0
info:
  version: 1.0.0
  title: Contact list
  description: >-
    This is an OpenAPI Specification created by oas-wizard
    (https://github.com/pafmon/oas-wizard)  
  contact:
    name: PabloFM
    email: pablofm@us.es
    url: 'http://www.isa.us.es'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/contacts:
    get:
      description: Returns all contacts
      operationId: getContacts
      responses:
        '200':
          description: Contact List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/contact'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    post:
      description: Creates a new contact
      operationId: addContact
      responses:
        '201':
          description: contact created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: contact
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contact'
        description: Contact to be created
        required: true
  '/api/v1/contacts/{name}':
    get:
      description: Returns a contact by name
      operationId: findContactByname
      parameters:
        - name: name
          in: path
          description: name of contact to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contact'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    delete:
      description: deletes a single contact based on the name
      operationId: deleteContact
      parameters:
        - name: name
          in: path
          description: ID of contact to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: contact deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      description: Update a contact based on its name
      operationId: updateContact
      parameters:
        - name: name
          in: path
          description: ID of contact to put
          required: true
          schema:
            type: string
      responses:
        '204':
          description: contact updated
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: contact
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contact'
        description: Contact to be updated
        required: true
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    contact:
      description: ''
      type: object
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        phone:
          type: number
      required:
        - name
        - email
        - phone
