version: '3'
services:
    contacts:
        build: .
        ports:
            - "127.0.0.1:${PORT}:8080"
        depends_on:
            - mongo
        restart: on-failure
        volumes: 
            - "logsvol:/app/logs"
        environment: 
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - DBPORT=${DBPORT}
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRUTAL_PORT=${PORT}
    mongo:
        image: "mongo"
        expose: 
            - "${DBPORT}"
        command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
        volumes: 
            - "database:/data/db"
            - "logsvol:/var/log/mongodb"
volumes: 
    database:
    logsvol:
        external: true

networks: 
    default: 
        external:
            name: service-tier
